logo = """

                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                       bbbbbbbb                                                  
        GGGGGGGGGGGGG                                                                                  tttt        hhhhhhh                                                                                             b::::::b                                                  
     GGG::::::::::::G                                                                               ttt:::t        h:::::h                                                                                             b::::::b                                                  
   GG:::::::::::::::G                                                                               t:::::t        h:::::h                                                                                             b::::::b                                                  
  G:::::GGGGGGGG::::G                                                                               t:::::t        h:::::h                                                                                              b:::::b                                                  
 G:::::G       GGGGGuuuuuu    uuuuuu     eeeeeeeeeeee       ssssssssss      ssssssssss        ttttttt:::::ttttttt   h::::h hhhhh          eeeeeeeeeeee         nnnn  nnnnnnnn   uuuuuu    uuuuuu    mmmmmmm    mmmmmmm  b:::::bbbbbbbbb       eeeeeeeeeeee   rrrrr   rrrrrrrrr   
G:::::G             u::::u    u::::u   ee::::::::::::ee   ss::::::::::s   ss::::::::::s       t:::::::::::::::::t   h::::hh:::::hhh     ee::::::::::::ee       n:::nn::::::::nn u::::u    u::::u  mm:::::::m  m:::::::mmb::::::::::::::bb   ee::::::::::::ee r::::rrr:::::::::r  
G:::::G             u::::u    u::::u  e::::::eeeee:::::ess:::::::::::::sss:::::::::::::s      t:::::::::::::::::t   h::::::::::::::hh  e::::::eeeee:::::ee     n::::::::::::::nnu::::u    u::::u m::::::::::mm::::::::::b::::::::::::::::b e::::::eeeee:::::er:::::::::::::::::r 
G:::::G    GGGGGGGGGu::::u    u::::u e::::::e     e:::::s::::::ssss:::::s::::::ssss:::::s     tttttt:::::::tttttt   h:::::::hhh::::::he::::::e     e:::::e     nn:::::::::::::::u::::u    u::::u m::::::::::::::::::::::b:::::bbbbb:::::::e::::::e     e:::::rr::::::rrrrr::::::r
G:::::G    G::::::::u::::u    u::::u e:::::::eeeee::::::es:::::s  ssssss s:::::s  ssssss            t:::::t         h::::::h   h::::::e:::::::eeeee::::::e       n:::::nnnn:::::u::::u    u::::u m:::::mmm::::::mmm:::::b:::::b    b::::::e:::::::eeeee::::::er:::::r     r:::::r
G:::::G    GGGGG::::u::::u    u::::u e:::::::::::::::::e   s::::::s        s::::::s                 t:::::t         h:::::h     h:::::e:::::::::::::::::e        n::::n    n::::u::::u    u::::u m::::m   m::::m   m::::b:::::b     b:::::e:::::::::::::::::e r:::::r     rrrrrrr
G:::::G        G::::u::::u    u::::u e::::::eeeeeeeeeee       s::::::s        s::::::s              t:::::t         h:::::h     h:::::e::::::eeeeeeeeeee         n::::n    n::::u::::u    u::::u m::::m   m::::m   m::::b:::::b     b:::::e::::::eeeeeeeeeee  r:::::r            
 G:::::G       G::::u:::::uuuu:::::u e:::::::e          ssssss   s:::::sssssss   s:::::s            t:::::t    ttttth:::::h     h:::::e:::::::e                  n::::n    n::::u:::::uuuu:::::u m::::m   m::::m   m::::b:::::b     b:::::e:::::::e           r:::::r            
  G:::::GGGGGGGG::::u:::::::::::::::ue::::::::e         s:::::ssss::::::s:::::ssss::::::s           t::::::tttt:::::h:::::h     h:::::e::::::::e                 n::::n    n::::u:::::::::::::::um::::m   m::::m   m::::b:::::bbbbbb::::::e::::::::e          r:::::r            
   GG:::::::::::::::Gu:::::::::::::::ue::::::::eeeeeeee s::::::::::::::ss::::::::::::::s            tt::::::::::::::h:::::h     h:::::he::::::::eeeeeeee         n::::n    n::::nu:::::::::::::::m::::m   m::::m   m::::b::::::::::::::::b e::::::::eeeeeeee  r:::::r            
     GGG::::::GGG:::G uu::::::::uu:::u ee:::::::::::::e  s:::::::::::ss  s:::::::::::ss               tt:::::::::::th:::::h     h:::::h ee:::::::::::::e         n::::n    n::::n uu::::::::uu:::m::::m   m::::m   m::::b:::::::::::::::b   ee:::::::::::::e  r:::::r            
        GGGGGG   GGGG   uuuuuuuu  uuuu   eeeeeeeeeeeeee   sssssssssss     sssssssssss                   ttttttttttt hhhhhhh     hhhhhhh   eeeeeeeeeeeeee         nnnnnn    nnnnnn   uuuuuuuu  uuummmmmm   mmmmmm   mmmmmbbbbbbbbbbbbbbbb      eeeeeeeeeeeeee  rrrrrrr            
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
"""